package br.com.bolao.domain.enums;

public enum ScoringKey {
    GROUP_EXACT_SCORE,
    GROUP_CORRECT_WINNER_AND_DIFF,
    GROUP_CORRECT_WINNER,
    GROUP_CORRECT_DRAW,
    KNOCKOUT_EXACT_SCORE,
    KNOCKOUT_CORRECT_WINNER_AND_DIFF,
    KNOCKOUT_CORRECT_WINNER,
    GROUP_CLASSIFICATION_CORRECT_PER_TEAM,
    GROUP_CLASSIFICATION_CORRECT_POSITION,
    GROUP_CLASSIFICATION_WRONG_POSITION,
    GROUP_THIRD_QUALIFIES,
    SEMIFINALISTS_CORRECT_PER_TEAM,
    TOP_SCORER_CORRECT
}
