package br.com.bolao.domain.enums;

public enum ScoringKey {
    GROUP_EXACT_SCORE,
    GROUP_CORRECT_WINNER_AND_DIFF,
    GROUP_CORRECT_WINNER,
    GROUP_CORRECT_DRAW,
    GROUP_CLASSIFICATION_CORRECT_POSITION,
    GROUP_CLASSIFICATION_WRONG_POSITION,
    GROUP_THIRD_QUALIFIES,
    TOP_SCORER_CORRECT,
    BRACKET_CORRECT_PICK
}
